export const CHECK_FRIEND = 'CHECK_FRIEND';
export const CHECK_FRIEND_SUCCESS = 'CHECK_FRIEND_SUCCESS';

export const ADD_FRIEND = 'ADD_FRIEND';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';

export const LIST_REQUEST_FRIEND = 'LIST_REQUEST_FRIEND';
export const LIST_REQUEST_FRIEND_SUCCESS = 'LIST_REQUEST_FRIEND_SUCCESS';

export const LIST_FRIEND = 'LIST_FRIEND';
export const LIST_FRIEND_SUCCESS = 'LIST_FRIEND_SUCCESS';

export const ACCEPT_FRIEND = 'ACCEPT_FRIEND';

export const DECLINE_FRIEND = 'DECLINE_FRIEND';

export const REMOVE_FRIEND = 'REMOVE_FRIEND';

export const FRIEND_ERROR = 'FRIEND_ERROR';