export const WATCH_INVITATION = 'WATCH_INVITATION';
export const WATCH_INVITATION_SUCCESS = 'WATCH_INVITATION_SUCCESS';

export const CREATE_INVITATION = 'CREATE_INVITATION';
export const CREATE_INVITATION_SUCCESS = 'CREATE_INVITATION_SUCCESS';

export const ACCEPT_INVITATION = 'ACCEPT_INVITATION';

export const DELETE_INVITATION = 'DELETE_INVITATION';

export const INVITATION_ERROR = 'DELETE_INVITATION_ERROR';