export const PAYMENTS = 'PAYMENTS';
export const PAYMENTS_SUCCESS = 'PAYMENTS_SUCCESS';

export const WATCH_TICKET_BUY = 'WATCH_TICKET_BUY';
export const WATCH_TICKET_BUY_SUCCESS = 'WATCH_TICKET_BUY_SUCCESS';

export const SEARCH_TICKET_BUY = 'WATCH_TICKET_BUY';
export const SEARCH_TICKET_BUY_SUCCESS = 'WATCH_TICKET_BUY_SUCCESS';

export const WATCH_ID_ACC_BUY = 'WATCH_ID_ACC_BUY';
export const WATCH_ID_ACC_BUY_SUCCESS = 'WATCH_ID_ACC_BUY_SUCCESS';

export const DELETED_PAYMENT = 'DELETED_PAYMENT';
export const DELETED_PAYMENT_SUCCESS = 'DELETED_PAYMENT_SUCCESS';

export const TRASH_PAYMENT = 'TRASH_PAYMENT';
export const TRASH_PAYMENT_SUCCESS = 'TRASH_PAYMENT_SUCCESS';

export const TRASH_PAYMENT_ADMIN = 'TRASH_PAYMENT_ADMIN';
export const TRASH_PAYMENT_ADMIN_SUCCESS = 'TRASH_PAYMENT_ADMIN_SUCCESS';

export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS';

export const FIND_PAYMENT = 'FIND_PAYMENT';
export const FIND_PAYMENT_SUCCESS = 'FIND_PAYMENT_SUCCESS';

export const DELETED_FOREVER_PAYMENT = 'DELETED_FOREVER_PAYMENT';
export const DELETED_FOREVER_PAYMENT_SUCCESS = 'DELETED_FOREVER_PAYMENT_SUCCESS';

export const RESTORE_TRASH_PAYMENT = 'RESTORE_TRASH_PAYMENT';
export const RESTORE_TRASH_PAYMENT_SUCCESS = 'RESTORE_TRASH_PAYMENT_SUCCESS';

export const TRANSACTION_PAYMENT = 'TRANSACTION_PAYMENT';
export const TRANSACTION_PAYMENT_SUCCESS = 'TRANSACTION_PAYMENT_SUCCESS';

export const COUNT_BUY = 'COUNT_BUY';
export const COUNT_BUY_SUCCESS = 'COUNT_BUY_SUCCESS';

export const LASTS_PAYMENTS = 'LASTS_PAYMENTS';
export const LASTS_PAYMENTS_SUCCESS = 'LASTS_PAYMENTS_SUCCESS';

export const REVENUE_PAYMENT = 'REVENUE_PAYMENT';
export const REVENUE_PAYMENT_SUCCESS = 'REVENUE_PAYMENT_SUCCESS';


export const ERROR = 'ERROR';