export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const UPDATE_USER_ADMIN = 'UPDATE_USER_ADMIN';
export const UPDATE_USER_ADMIN_SUCCESS = 'UPDATE_USER_ADMIN_SUCCESS';

export const DELETED_USER = 'DELETED_USER';
export const DELETED_USER_SUCCESS = 'DELETED_USER_SUCCESS';

export const TRASH_USER = 'TRASH_USER';
export const TRASH_USER_SUCCESS = 'TRASH_USER_SUCCESS';

export const DELETED_FOREVER_USER = 'DELETED_FOREVER_USER';
export const DELETED_FOREVER_USER_SUCCESS = 'DELETED_FOREVER_USER_SUCCESS';

export const RESTORE_TRASH_USER = 'RESTORE_TRASH_USER';
export const RESTORE_TRASH_USER_SUCCESS = 'RESTORE_TRASH_USER_SUCCESS';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const FIND_USER = 'FIND_USER';
export const FIND_USER_SUCCESS = 'FIND_USER_SUCCESS';

export const COUNT_USER = 'COUNT_USER';
export const COUNT_USER_SUCCESS = 'COUNT_USER_SUCCESS';

export const LASTS_USER = 'LASTS_USER';
export const LASTS_USER_SUCCESS = 'LASTS_USER_SUCCESS';

export const TRANSACTIONS_USER = 'TRANSACTIONS_USER';
export const TRANSACTIONS_USER_SUCCESS = 'TRANSACTIONS_USER_SUCCESS';

export const GET_ALL_ID_USER = 'GET_ALL_ID_USER';
export const GET_ALL_ID_USER_SUCCESS = 'GET_ALL_ID_USER_SUCCESS';

export const SIGN_ERROR = 'SIGN_ERROR';

export const SIGN_OUT = 'SIGN_OUT';
