export const GET_STORIES = 'GET_STORIES';
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';

export const ADD_STORIES = 'ADD_STORIES';
export const ADD_STORIES_SUCCESS = 'ADD_STORIES_SUCCESS';

export const DELETE_STORIES = 'DELETE_STORIES';
export const DELETE_STORIES_SUCCESS = 'DELETE_STORIES_SUCCESS';

export const STORIES_ERROR = 'STORIES_ERROR';