export const GET_TICKETS = 'GET_TICKETS';
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';

export const GET_TICKETS_APPROVAL = 'GET_TICKETS_APPROVAL';
export const GET_TICKETS_APPROVAL_SUCCESS = 'GET_TICKETS_SUCCESS';

export const FILTER_TICKETS = 'FILTER_TICKETS';
export const FILTER_TICKETS_SUCCESS = 'FILTER_TICKETS_SUCCESS';

export const FILTER_TICKETS_BY_AUTHOR = 'FILTER_TICKETS_BY_AUTHOR';
export const FILTER_TICKETS_BY_AUTHOR_SUCCESS = 'FILTER_TICKETS_BY_AUTHOR_SUCCESS';

export const LOAD_MORE = 'LOAD_MORE';
export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS';

export const FIND_ID_TICKET = 'FIND_ID_TICKET';
export const FIND_ID_TICKET_SUCCESS = 'FIND_ID_TICKET_SUCCESS';

export const CREATE_TICKET = 'CREATE_TICKET';
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS';

export const WATCH_TICKET_SELL = 'WATCH_TICKET_SELL';
export const WATCH_TICKET_SELL_SUCCESS = 'WATCH_TICKET_SELL_SUCCESS';

export const GET_ALL_ID = 'GET_ALL_ID';
export const GET_ALL_ID_SUCCESS = 'GET_ALL_ID_SUCCESS';

export const UPDATE_TICKET = 'UPDATE_TICKET';
export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS';

export const UPDATE_TICKET_ADMIN = 'UPDATE_TICKET_ADMIN';
export const UPDATE_TICKET_ADMIN_SUCCESS = 'UPDATE_TICKET_ADMIN_SUCCESS';

export const ACCEPT_TICKET = 'ACCEPT_TICKET';
export const ACCEPT_TICKET_SUCCESS = 'ACCEPT_TICKET_SUCCESS';

export const DELETED_TICKETS = 'DELETED_TICKETS';
export const DELETED_TICKETS_SUCCESS = 'DELETED_TICKETS_SUCCESS';

export const TRASH_TICKETS = 'TRASH_TICKETS';
export const TRASH_TICKETS_SUCCESS = 'TRASH_TICKETS_SUCCESS';

export const TRASH_TICKETS_ADMIN = 'TRASH_TICKETS_ADMIN';


export const GET_TICKETS_ADMIN = 'GET_TICKETS_ADMIN';
export const GET_TICKETS_ADMIN_SUCCESS = 'GET_TICKETS_ADMIN_SUCCESS';

export const DELETED_FOREVER_TICKETS = 'DELETED_FOREVER_TICKETS';
export const DELETED_FOREVER_TICKETS_SUCCESS = 'DELETED_FOREVER_TICKETS_SUCCESS';

export const RESTORE_TRASH_TICKETS = 'RESTORE_TRASH_TICKETS';
export const RESTORE_TRASH_TICKETS_SUCCESS = 'RESTORE_TRASH_TICKETS_SUCCESS';

export const COUNT_SELL_TICKETS = 'COUNT_SELL_TICKETS';
export const COUNT_SELL_TICKETS_SUCCESS = 'COUNT_SELL_TICKETS_SUCCESS';

export const NUMBER_TICKETS = 'NUMBER_TICKETS';
export const NUMBER_TICKETS_SUCCESS = 'NUMBER_TICKETS_SUCCESS';

export const ERROR = 'ERROR';

